media:
  input: src/posts/assets/images
  output: /posts/assets/images
content:
  - name: posts
    label: Posts
    path: src/posts
    type: collection
    filename: "{primary}.md"
    view:
      fields: [ title, date ]
      primary: title
      sort: [ date, title ]
      default:
        sort: date
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true}
      - { name: description, label: Description, type: string, options: {maxlength: 180}}
      - { name: date, label: Date, type: rich-text}
      - { name: body, label: Body, type: rich-text}
      - { name: image, label: Image, type: image}