media:
  input: src/posts/assets/images
  output: /posts/assets/images
content:
  - name: posts
    label: Tusixmode
    path: src/posts
    type: collection
    filename: "{primary}.md"
    view:
      fields: [title, date]