media:
  input: src/posts/assets/images
  output: /posts/assets/images
content:
  - name: posts
    label: Posts
    path: src/posts
    type: collection
content:
  - name: page
    label: all page setting
    path: /
    type: setting