media:
  input: src/posts/assets/images
  output: /posts/assets/images
content:
  - name: posts
    label: Posts
    path: src/posts
    type: collection
    filename: "{primary}.md"
    view:
      fields: [ title, date ]
      primary: title
      sort: [ date, title ]
      default:
        sort: date
        order: desc
    fields:
      - { name: title, label: Title, type: string, required: true}
      - { name: description, label: Description, type: string, options: {maxlength: 180}}
      - { name: date, label: Date, type: date, options: {format: yyyy-MM-dd'T'HH:mm:ss, time: true}}
      - { name: tags, label: Tags, type: string, list: {collapsible: true, min: 1, max: 5, default: [new]}}
      - { name: body, label: Body, type: rich-text}
      - { name: image, label: Image, type: image}