media:
  input: src/posts/assets/images
  output: /posts/assets/images
content:
  - name: posts
    label: Tusixmode
    path: src/posts/tusixmode
    type: collection
    filename: "{primary}.md"
  - name: posts
    label: Triết học tinh thần
    path: src/posts/article
    type: collection